services:
  postgres:
    image: postgres:17
    container_name: crrencyRates-postgres
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - candidate_postgres_data:/var/lib/postgresql/data

volumes:
  candidate_postgres_data: